### ISSUE TITLE
POST and PATCH requests for content_link_menu return 500 error although the request was sucessful

### ISSUE THREAD

**Issue by ericpugh** [ericpugh/drupal-content-direct#18]
error: 
`LogicException: The controller result claims to be providing relevant cache metadata, but leaked metadata was detected. Please ensure you are not rendering content too early. Returned object class: Drupal\rest\ResourceResponse. in Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext() (line 154 of /var/www/drupalvm/drupal2/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php).`

**Comment by ericpugh** [comment]
related to #16

**Comment by bhasselbeck** [comment]
This is related to https://www.drupal.org/node/2626298
