### ISSUE TITLE
File entity 422 "unprocessable entity" request errors when site's are not clones of each other

### ISSUE THREAD

**Issue by ericpugh** [ericpugh/drupal-content-direct#21]
When using Content Direct on two different sites, File Entities will not be created returning a 415 response code. However, If the two sites using Content Direct are copies of each other, (i.e. cloned databases) then the request will work as intended.

**Comment by bhasselbeck** [comment]
1. If the database is cloned from an existing site, it works properly.
2. But a separate database that isn't cloned comes back with an error, 415 unsupported media type, which is an invalid method request.
3. Only for taxonomy terms and files entities

UUIDs may not correlate between sites. Ensure that the sites are synchronized
